---
name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: setup tools
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: check lockfile
        run: deno task deps:check

      - name: check lint
        run: |
          deno lint
          yamllint .

      - name: check format
        run: |-
          deno fmt --check
          yamlfmt -dry -lint .

      - name: run tests
        run: deno test
